# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmQwOWZiY2NkMWFjNzJkYjI2OWE1NjRhODYzNGYwMGQzNGFhMjBkYWU1YzM0YWI2MzZkZGI5ZmU1NmE2NDI2YjY0OGIzZTA0MTEzMzVmMTA2ZmQ0NGJlOTNmMjc0NTMxNDE0NmMyYmNiMjgxNjRjY2FjN2ZhOGE1ZjNjM2E3OTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
